{
 "title": "IoT_Blagnac",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "salles", "query": "SHOW TAG VALUES with key=salle" },
   { "name": "etages", "query": "SHOW TAG VALUES with key=etage" },
   {
    "name": "batiment",
    "query": "SHOW TAG VALUES with key=batiment"
   },
   { "name": "measurements", "query": "show measurements" }
  ]
 },
 "panels": [
  { "title": "$batiment", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "batiment" },
  {
   "title": "Direct $measurements $salles",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "repeat": "measurements",
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_salle",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "batiment" ], "type": "tag" },
      { "params": [ "etage" ], "type": "tag" },
      { "params": [ "salle" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurements$/",
     "query": "SELECT last(\"value\") FROM /^$measurements$/ WHERE (\"salle\" =~ /^$salles$/ AND \"etage\" =~ /^$etages$/ AND \"batiment\" =~ /^$batiment$/) AND $timeFilter GROUP BY time($__interval), \"batiment\", \"etage\", \"salle\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "salle", "operator": "=~", "value": "/^$salles$/" },
      { "condition": "AND", "key": "etage", "operator": "=~", "value": "/^$etages$/" },
      { "condition": "AND", "key": "batiment", "operator": "=~", "value": "/^$batiment$/" }
     ]
    },
    {
     "alias": "unit",
     "query": "SHOW TAG VALUES from /^$measurements$/ with key=unit"
    }
   ]
  },
  {
   "title": "Moyenne $measurements etage : $etages",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "repeat": "measurements",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "/^$measurements$/",
     "query": "SELECT mean(\"value\") FROM /^$measurements$/ WHERE (\"etage\" =~ /^$etages$/ AND \"batiment\" =~ /^$batiment$/) AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "etage", "operator": "=~", "value": "/^$etages$/" },
      { "condition": "AND", "key": "batiment", "operator": "=~", "value": "/^$batiment$/" }
     ]
    },
    {
     "query": "SHOW TAG VALUES from /^$measurements$/ with key=unit"
    }
   ]
  },
  {
   "title": "Average $measurements $batiment",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "repeat": "measurements",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_etage, $tag_salle",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "batiment" ], "type": "tag" },
      { "params": [ "etage" ], "type": "tag" },
      { "params": [ "salle" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurements$/",
     "query": "SELECT last(\"value\") FROM /^$measurements$/ WHERE (\"batiment\" =~ /^$batiment$/ AND \"etage\" =~ /^$etages$/ AND \"salle\" =~ /^$salles$/) AND $timeFilter GROUP BY time($__interval), \"batiment\", \"etage\", \"salle\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "batiment", "operator": "=~", "value": "/^$batiment$/" },
      { "condition": "AND", "key": "etage", "operator": "=~", "value": "/^$etages$/" },
      { "condition": "AND", "key": "salle", "operator": "=~", "value": "/^$salles$/" }
     ]
    },
    {
     "query": "SHOW TAG VALUES from /^$measurements$/ with key=unit"
    }
   ]
  },
  {
   "title": "$measurements $salles",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "repeat": "measurements",
   "targets": [
    {
     "alias": "$tag_etage, $tag_salle",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "batiment" ], "type": "tag" },
      { "params": [ "etage" ], "type": "tag" },
      { "params": [ "salle" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurements$/",
     "query": "SELECT last(\"value\") FROM /^$measurements$/ WHERE (\"batiment\" =~ /^$batiment$/ AND \"etage\" =~ /^$etages$/ AND \"salle\" =~ /^$salles$/) AND $timeFilter GROUP BY time($__interval), \"batiment\", \"etage\", \"salle\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "batiment", "operator": "=~", "value": "/^$batiment$/" },
      { "condition": "AND", "key": "etage", "operator": "=~", "value": "/^$etages$/" },
      { "condition": "AND", "key": "salle", "operator": "=~", "value": "/^$salles$/" }
     ]
    },
    {
     "query": "SHOW TAG VALUES from /^$measurements$/ with key=unit"
    }
   ]
  },
  {
   "title": "Minimum $measurements $batiment",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "repeat": "measurements",
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "alias": "$tag_etage, $tag_salle",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "batiment" ], "type": "tag" },
      { "params": [ "etage" ], "type": "tag" },
      { "params": [ "salle" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurements$/",
     "query": "SELECT last(\"value\") FROM /^$measurements$/ WHERE (\"batiment\" =~ /^$batiment$/ AND \"etage\" =~ /^$etages$/ AND \"salle\" =~ /^$salles$/) AND $timeFilter GROUP BY time($__interval), \"batiment\", \"etage\", \"salle\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "batiment", "operator": "=~", "value": "/^$batiment$/" },
      { "condition": "AND", "key": "etage", "operator": "=~", "value": "/^$etages$/" },
      { "condition": "AND", "key": "salle", "operator": "=~", "value": "/^$salles$/" }
     ]
    },
    {
     "query": "SHOW TAG VALUES from /^$measurements$/ with key=unit"
    }
   ]
  },
  {
   "title": "Maximum $measurements $batiment",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "repeat": "measurements",
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "alias": "$tag_etage, $tag_salle",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "batiment" ], "type": "tag" },
      { "params": [ "etage" ], "type": "tag" },
      { "params": [ "salle" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurements$/",
     "query": "SELECT last(\"value\") FROM /^$measurements$/ WHERE (\"batiment\" =~ /^$batiment$/ AND \"etage\" =~ /^$etages$/ AND \"salle\" =~ /^$salles$/) AND $timeFilter GROUP BY time($__interval), \"batiment\", \"etage\", \"salle\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "batiment", "operator": "=~", "value": "/^$batiment$/" },
      { "condition": "AND", "key": "etage", "operator": "=~", "value": "/^$etages$/" },
      { "condition": "AND", "key": "salle", "operator": "=~", "value": "/^$salles$/" }
     ]
    },
    {
     "query": "SHOW TAG VALUES from /^$measurements$/ with key=unit"
    }
   ]
  }
 ]
}