<?php
date_default_timezone_set("Europe/Paris");
include ("mysql.php");                                                          /* Include credential and DB name*/
	$requete = "SELECT capteur.id, capteur.topic FROM capteur;";
				$resultat = mysqli_query($id_bd, $requete)						/*Get all sensors id and topics from the DB*/
					or die("Execution de la requete impossible : $requete"); 
	$capteur = array();															/*Declare 'capteur' as an array*/
    while($ligne=mysqli_fetch_assoc($resultat))									
	{	
	extract($ligne);															/*Parse column name of the table as variables*/
	$capteur[] = array('topic' => $topic, 'capteur_id' => $id);					/*Create an associative array with the 'topic' and 'capteur_id' column of the capteur table*/
	}

	$capteur_size = count($capteur);											/*Count the number of sensors*/

	for ($i = 0; $i <= $capteur_size - 1; $i++)									/*Repeat for the number of sensors */
	{
		$topic = $capteur[$i]["topic"];											/*Put the 'i' topic and sensors id into variables*/
		$capteur_id = $capteur[$i]["capteur_id"];								/*######################################*/
		$value = shell_exec("mosquitto_sub -h mqtt -t $topic -C 1 -F %p");		/*Listen for the payload*/
		$date = date("Y-m-d");													/*Generate date and time pattern*/
		$time = date("H:i:s");													/*##############################*/
		$requete = "INSERT INTO mesure (date, heure) VALUES ('$date', '$time');"; /*Insert date and time into the 'measure' table*/ 
		mysqli_query($id_bd, $requete)
			or die("Execution de la requete impossible : $requete");
		$requete = "SELECT mesure.id FROM mesure ORDER BY id DESC LIMIT 1;";     /*Get the ID generated by the last request (last one)*/
		$resultat = mysqli_query($id_bd, $requete)
			or die("Execution de la requete impossible : $requete");
		$ligne=mysqli_fetch_assoc($resultat);												
		extract($ligne);														/*Parse column name of the table as variables*/
		$requete = "INSERT INTO valeur (valeur, id_capteur, id_mesure) VALUES ('$value', '$capteur_id', '$id');"; /*Insert sensor value into the 'valeur' table with the matching id of the last request */
		mysqli_query($id_bd, $requete)
			or die("Execution de la requete impossible : $requete");
		printf("%s %s %s\n", $topic, $date, $time);	/*Log*/
	}
	mysqli_close($id_bd);
?>